-- MySQL Workbench Synchronization
-- Generated: 2022-11-06 13:06
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: HP

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `Tickets` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `Tickets`.`Usuario` (
  `Codigo` NVARCHAR(20) NOT NULL,
  `Nombre` NVARCHAR(50) NOT NULL,
  `Clave` NVARCHAR(120) NOT NULL,
  `Rol` NVARCHAR(120) NOT NULL,
  `Correo` NVARCHAR(120) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Tickets`.`TipoSoporte` (
  `Codigo` INT(11) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Precio` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Tickets`.`Ticket` (
  `Codigo` INT(11) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `CodigoUsuario` NVARCHAR(20) NOT NULL,
  `NombreCliente` NVARCHAR(20) NOT NULL,
  `TipoSoporte` NVARCHAR(50) NOT NULL,
  `Descripcion` NVARCHAR(50) NOT NULL,
  `DescripcionRespuesta` NVARCHAR(50) NOT NULL,
  `Precio` DECIMAL(8,2) NOT NULL,
  `Impuesto` DECIMAL(8,2) NOT NULL,
  `Descuento` DECIMAL(8,2) NOT NULL,
  `SubTotal` DECIMAL(8,2) NOT NULL,
  `Total` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
